all: dhcpstarve.cpp
	# -Wmissing-field-initializers is needed because g++ complains about default initializers...
	g++ -std=c++11 -Wall -Wextra -Wno-missing-field-initializers -pedantic -o ipk-dhcpstarve dhcpstarve.cpp
